var MAXENEMIES = 100;
var MAXROCKS = 100;
var BIGROCK = 50;
var SMALLROCK = 20;
var NumRocks = 5;
var NumParticles = 5;
var ShipExplodeCount = 100;
var NumEnemies = 5;
var ShipSize = 30;
//var shipPic;
var gameOverText;
var gameOver = false;
var Score=0;
var HighScore=0;
var RocksLeft;
var ShipsLeft;
var gameStart = false;
var introTextSize = .01;
var introText;
var introText2;
var spaceKey;
var leftKey;
var rightKey;
var upKey;
var downKey;
var MainShip;
var Enemies = [];
var Explosion = [];
var Particles = [];
var Rocks = [];
var Bullets = [];
var EnemyBullets = [];
var Pie = 3.14159265358979;
var Radians = (2 * Pie) / 360;
var shipLine = [];
var bulletLine = [];
 var enemyBulletLine = [];
var enemyLine = [];
var ShipsLeft = 5;
var RockNumStart = 4;
var Level = 1;
var infoText2;
var bulletup = 1;